apiVersion: v1
kind: Secret
metadata:
  name: doc-db-credentials
type: Opaque
data:
  custom-user: {{ .Values.secrets.doc_db_credentials.custom_user | b64enc | quote }}
  custom-pwd: {{ .Values.secrets.doc_db_credentials.custom_pwd | b64enc | quote }}
  metrics-pwd: {{ .Values.secrets.doc_db_credentials.metrics_pwd | b64enc | quote }}
  replica-user: {{ .Values.secrets.doc_db_credentials.replica_user | b64enc | quote }}
  replica-pwd: {{ .Values.secrets.doc_db_credentials.replica_pwd | b64enc | quote }}
  super-pwd: {{ .Values.secrets.doc_db_credentials.super_pwd | b64enc | quote }}