apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eric-cbrs-dc.name" . }}-gp
  labels:
    app.kubernetes.io/name: {{ include "eric-cbrs-dc.name" . }}
    app.kubernetes.io/version: {{ include "eric-cbrs-dc.version" . }}
    chart: {{ template "eric-cbrs-dc.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- include "eric-cbrs-dc.config-labels" .| indent 4 }}
  annotations:
{{- include "eric-cbrs-dc.product-info" . | indent 4 }}
{{- include "eric-cbrs-dc.config-annotations" .| indent 4 }}
data:
  global.properties: |
    DDC_ON_CLOUD=TRUE
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eric-cbrs-dc.name" . }}-gp-pg-pass
  labels:
    app.kubernetes.io/name: {{ include "eric-cbrs-dc.name" . }}
    app.kubernetes.io/version: {{ include "eric-cbrs-dc.version" . }}
    chart: {{ template "eric-cbrs-dc.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- include "eric-cbrs-dc.config-labels" .| indent 4 }}
  annotations:
{{- include "eric-cbrs-dc.product-info" . | indent 4 }}
{{- include "eric-cbrs-dc.config-annotations" .| indent 4 }}
data:
  global.properties: |
    postgresql01_admin_password={{ .Values.techDebt.enmProperties.postgresql01_admin_password }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eric-cbrs-dc.name" . }}-pg-key
  labels:
    app.kubernetes.io/name: {{ include "eric-cbrs-dc.name" . }}
    app.kubernetes.io/version: {{ include "eric-cbrs-dc.version" . }}
    chart: {{ template "eric-cbrs-dc.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- include "eric-cbrs-dc.config-labels" .| indent 4 }}
  annotations:
{{- include "eric-cbrs-dc.product-info" . | indent 4 }}
{{- include "eric-cbrs-dc.config-annotations" .| indent 4 }}
data:
  postgresql01_passkey: |
    5EacabwlanIHjZ8XAkoPIA==