apiVersion: v1
kind: Service
metadata:
  name: {{ template "eric-cbrs-dc.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "eric-cbrs-dc.name" . }}
    app.kubernetes.io/version: {{ include "eric-cbrs-dc.version" . }}
    chart: {{ template "eric-cbrs-dc.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- include "eric-cbrs-dc.config-labels" .| indent 4 }}
  annotations:
{{- include "eric-cbrs-dc.product-info" . | indent 4 }}
{{- include "eric-cbrs-dc.config-annotations" .| indent 4 }}
    {{- if .Values.ingress.ingressClass }}
    kubernetes.io/ingress.class: {{.Values.ingress.ingressClass }}
    {{- end }}
    prometheus.io/scrape: "true"
    prometheus.io/port: "9600"
spec:
  type: {{ .Values.service.internalService.type }}
{{- if .Values.global }}
  {{- if .Values.global.internalIPFamily }}
  ipFamily: {{ .Values.global.internalIPFamily }}
  {{- end }}
{{- end }}
  ports:
    - name: jboss
      port: {{ .Values.service.jbossPort }}
      targetPort: jboss-port
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics-port
  selector:
    app.kubernetes.io/name: {{ template "eric-cbrs-dc.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "eric-cbrs-dc.name" . }}-akka
  labels:
    app.kubernetes.io/name: {{ include "eric-cbrs-dc.name" . }}
    app.kubernetes.io/version: {{ include "eric-cbrs-dc.version" . }}
    chart: {{ template "eric-cbrs-dc.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- include "eric-cbrs-dc.config-labels" .| indent 4 }}
  annotations:
{{- include "eric-cbrs-dc.product-info" . | indent 4 }}
{{- include "eric-cbrs-dc.config-annotations" .| indent 4 }}
spec:
{{- if .Values.global }}
  {{- if .Values.global.internalIPFamily }}
  ipFamily: {{ .Values.global.internalIPFamily }}
  {{- end }}
{{- end }}
  ports:
    - name: akka-mgmt
      port: {{ .Values.service.akkaManagementPort }}
      targetPort: akka-mgmt-port
    - name: akka-probing
      port: {{ .Values.service.akkaProbingPort }}
      targetPort: akka-probe-port
  selector:
    app.kubernetes.io/name: {{ template "eric-cbrs-dc.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
  clusterIP: None
  publishNotReadyAddresses: true
